### ISSUE TITLE
Add support to control lights witch switches

### ISSUE THREAD

**Issue by ttalonso** [valterc/ki2#105]
Within the control options. Navigate left / rigth, go to the map screen, etc... It would be interesting to be able to turn lights on/off, as is allowed in Garmin. Is it possible?

**Comment by valterc** [comment]
Good suggestion! 
Honestly not sure if we can do that, Karoo SDK has no support for it... something to research.

**Comment by valterc** [comment]
Unfortunately this is not really possible at this time. There is no support from Karoo and I've looked at several options but nothing looks stable enough to develop.
