### ISSUE TITLE
Number of Syncro Attention Beeps 

### ISSUE THREAD

**Issue by dcquad** [valterc/ki2#120]
The default number of beeps seems to be 3. could this be reduced?  I appreciate having an audio reminder of the upcoming shift etc. but the default number is tooo many! I also use the varia radar and the combo is overwhelming. I'd like just one beep for the di2 integration.

thnx, Doug

**Comment by valterc** [comment]
Unfortunately this is not really possible. 
I could perhaps add an option to choose the beep pattern, but the choices are limited to what Karoo provides. So we cannot easily just beep once, we need to 'play' an existing beep pattern.

**Comment by ttalonso** [comment]
For me the current beep is perfect. Please, do not touch!
In any case, always giving the user the option is welcome!
