### ISSUE TITLE
Add support to remote 

### ISSUE THREAD

**Issue by lockevod** [valterc/ki2#122]
Hello! You’ve added support to di2 remotes like titan kommander (problem kommander is out of stock and it’s difficult to buy if you are in Spain etc). 

You’re app it’s very interesting for gear but also for remote for Karoo (map etc). 

Could you add support to garmin remote (not for di2 gears), but only for change screens etc. function that you have developed ;)

Regard
PS:I don’t know another remote (titan or garmin remote only)

thanks

**Comment by lockevod** [comment]
Thanks for your answer. I understand :)

My problem is I don’t have di2, it’s only i triunfo to find something to
change screens when I use my Karoo.

But I think only kommander can be used heat without di2 group

Thanks

**Comment by valterc** [comment]
I see, you should try to request those features to Hammerhead on their community pages: https://support.hammerhead.io/hc/en-us/community/topics

For the moment I will not implement support for Garmin Remote.
