### ISSUE TITLE
Problem with Titan Lab Kommander after holding switch

### ISSUE THREAD

**Issue by galvar61** [valterc/ki2#125]
I use the Ki2 for screen management with the Titan Lab Kommander. Since I updated to v 2.0 when I start the route it stops working.

**Comment by valterc** [comment]
Hi, I don't have a Kommander to test with, so you need to provide more details, otherwise I cannot fix this.

**Comment by galvar61** [comment]
First of all thanks for answering.
I start the Karoo 2 and the Ki2 app recognizes the Kommander. Signal
strength of 65-75 dB. Manage device enable.
Before beginning the route, correct operation of the buttons with
their programmed functions.
I start the route and after several presses (I have tried 7-8 times)
the Karoo's low battery alarm goes off in the Di2 and the Kommander
buttons stop working. I need to reboot the Karoo to start over.

Saludos,   Gerardo Alvarez

**Comment by valterc** [comment]
Typically a low battery alert only happens when the Di2 device has low battery. Is there a way to check battery level of Kommander?

You can also try to check the battery of Kommander from Ki2, open the device details of Kommander, and scroll down until you see the battery. Try to press the buttons a few times on that screen, there is also display of the button events if you scroll to the bottom.

**Comment by galvar61** [comment]
I have been doing tests with the previous battery (at 35%) and with a new one (100%), with the same results.
At the bottom of the app, where the effect of each button press is shown, it is displayed correctly UNTIL I make a long press, regardless of whether it has a function assigned to it or not. From that moment that button stops working.
To go back to the start I need to restart the Karoo and sometimes the buttons don't work like that either.
It really is a bit anarchic,
And I don't know if it will depend more on Kommader than on your application, which until I did the update worked great. Thanks for your attention.

**Comment by valterc** [comment]
What happens when you hold a button? Does it say 'Holding' in Ki2 details? if yes, does the 'Holding' go away after you release the button?

This is tricky for me to debug, I don't have a Kommander, it might be some problem in the way Kommander sends the button events.

**Comment by valterc** [comment]
Did some check on Ki2 and I don't see any potential problems, so it's likely that the issues is on Kommander side? Unfortunately I don't have access to a Kommander for further testing 😐

It seems that the low battery problem is also well known, so maybe try to update Kommander to latest firmware and if it still does not fix it, try reaching out to their support.

This what they state in their website:

> We are aware of false positive battery warnings. Please ensure you are on the latest firmware of the application as filtering was improved. Some head units tend to freak out we’ve found.
> Some of this is related to the battery connection. Under vibration the unit disconnects but takes 1 – 2 seconds to discharge the caps, as such when the unit reboots a Windows or macOS computer will reconnect immediately assuming it was just interference. The BLE characteristic must be requested from the host side to update, since the device rebooted and the computer assumes it was just interference the computer thinks it’s requested the update already while the device has not. This means that under these circumstances the batter level gets stuck on a false low. Disconnecting and reconnecting will force the computer to request the battery updates.
> Contact support@titanlab.co for instructions on fixing the battery connection or replacement.

**Comment by galvar61** [comment]
I have the Kommander with the latest firmware update.
Thank you Valterc for your time and dedication.
For now I'll avoid long presses on the switches.😁

Un saludo, Gerardo Alvarez
