### ISSUE TITLE
Add shifting information to FIT file

### ISSUE THREAD

**Issue by valterc** [valterc/ki2#13]

**Comment by valterc** [comment]
Karoo SDK supports reading the FIT file after the ride is complete, but there is no official support for adding/editing values in the FIT file. It would be possible to hack something up, but it would be very sketchy and not worth potentially corrupting the FIT file, as we cannot guarantee exclusive access to the file.

**Comment by kintrupf** [comment]
I agree that it's not a good idea to "hack" the .fit file during a ride.
But can you probably record the gear information in some other way, perhaps into a small SQLite database or something like that? I would love to know which gears I use the most. And maybe you can "hack" the information back into a _copy_ of the .fit file _after_ the ride is complete?

**Comment by valterc** [comment]
I could re-visit this again. We can definitely store the gear 'usage' metrics during rides, but if that info is hard to extract from Karoo then it won't have much value.

I will try to explore again and if it's worth perhaps to make an option to replace the fit file.

**Comment by valterc** [comment]
With some 'clever' workarounds it is possible to inject the gear shift information in the Ride FIT file. Since this is not an official API in Karoo it might break in a future Karoo software version - could corrupt the FIT file.

I added it under a setting that is disabled by default.

**Comment by valterc** [comment]
Probably next week, I still need to do more testing (bigger rides) to make sure all is good 🙂
