### ISSUE TITLE
Want to buy a coffee

### ISSUE THREAD

**Issue by akivanwasser** [valterc/ki2#136]
I really appreciate the work and timeyou put in to this app and would like to buy you a coffee. However, I can't find the link. Can you post it here?

**Comment by valterc** [comment]
Hi, you can buy me a coffee via this link: https://www.paypal.com/donate/?business=N6PWH859NY7W6&no_recurring=1&item_name=Buy+me+a+coffee&currency_code=EUR

Thank you!
