### ISSUE TITLE
No data displayed for gear count, Gears, shift battery, 

### ISSUE THREAD

**Issue by Sirkaos56** [valterc/ki2#137]
Version 2.0, I do have drivetrain and it works well and really like that display. Hood buttons are working well and I checked that buttons only was not selected. 
Side note, are you in Ukraine? I spent quite a bit of time there about 10 years ago, various cities. Loved it.

**Comment by valterc** [comment]
Hi, if you open the details of the shifter in Ki2 do you see battery % and gearing information there? Should be similar to this image:
![image](https://user-images.githubusercontent.com/1299179/225885147-c92602d9-b749-43d5-ba85-b5a336284b8f.png)

Keep in mind that in Karoo Ride Profiles, you need to replace all data elements with the ones from Ki2, for example if you have `Shf Bat %` from Karoo it won't show any data from Ki2, you need to use the element from Ki2 in the profile - even if the name is the same.

Post a picture of the details in Ki2 and the ride with the data problems.

**Comment by Sirkaos56** [comment]
As you described, I have replaced all the data elements from Ki2. The shift battery % shows up when I open up the connected Ki2 menu but does not display in the data fields. I currently don't have Shift battery %, shift count, Gears or similar. I do have drive train and hood switch functions which is fantastic. Any ideas?

**Comment by valterc** [comment]
No ideas. Those fields use the same information that the Drivetrain uses, so that's really weird. Can you post a screenshot/picture of the ride elements and the Ki2 gearing information?
What is displayed in the ride elements in 'Shift battery %', 'shift count', 'Gears'?

**Comment by Sirkaos56** [comment]
I downloaded your 3.0 update and it looks like everything is perfect! All the missing data fields suddenly populated.  I didnt change anything other than doing your latest update. No idea why.

**Comment by valterc** [comment]
Ok, thanks for updating :)
