### ISSUE TITLE
Teeth programming

### ISSUE THREAD

**Issue by Corth1** [valterc/ki2#138]
how can I program the number of teeth on the cassette and the front sprockets?

**Comment by valterc** [comment]
Hi, in the current release version that is not yet possible. Ki2 will only detect the gearing from the Di2 system. You can configure that in E-Tube.
![image](https://user-images.githubusercontent.com/1299179/225961964-0eccbdd4-1467-4fce-838d-67b427a02bf0.png)

Not all Di2 systems are supported, if that is your case, you need to wait for next Ki2 version which will have support for configurable gearing.

**Comment by valterc** [comment]
Configurable gearing is now supported in version 3.0! It should prompt to update if you have the previous version installed in the Karoo.

**Comment by Corth1** [comment]
Thanks!!
