### ISSUE TITLE
Better visibility of "synchro" and "limit" in overlay

### ISSUE THREAD

**Issue by kintrupf** [valterc/ki2#155]
The "synchro" and "limit" displays in the overlay could stand out more. Perhaps use a bold yellow font in dark mode and a bold red font in light mode?
And maybe move the text more to the lower right corner, so that it is stands out even more?

**Comment by valterc** [comment]
I will try to mock some changes to see how they look/feel like. Not sure about changing colors for now, can make the UI a bit messier but will try.

The stand out part for synchro and limit is that they blink :)

**Comment by valterc** [comment]
Made the synchro/limit font bolder. Will be available in next update 🙂
