### ISSUE TITLE
Shift count in error

### ISSUE THREAD

**Issue by jschriesheim** [valterc/ki2#184]
Running latest version on today's ride. After 15-20 miles I changed from my main page to a page with a Ki2 shift count field. The shiftcount was very low (maybe 0), but then over the remainder of the ride it seemed to be recording shifts. When I look at the Hammerhead dashboard, the graph for "shifts" seems to have captured all the changes. Is this something you know about? Do I need to do something at startup to help Ki2 maintain the shiftcount field?

**Comment by valterc** [comment]
This will be fixed by the new version using Karoo Extensions.
