### ISSUE TITLE
karoo 1

### ISSUE THREAD

**Issue by acoucke** [valterc/ki2#201]
Is only version 0.8-karoo1 compatible with karoo 1 or is version 5.0 also compatible with karoo 1?

**Comment by valterc** [comment]
Hi, for Karoo 1 the only compatible version is the [0.8-karoo1](https://github.com/valterc/ki2/releases/tag/0.8-karoo1). Unfortunately Karoo 1 uses an older Android version and has some limitations, so the other releases will not work.

The version [0.8-karoo1](https://github.com/valterc/ki2/releases/tag/0.8-karoo1) is outdated but will work fine and provides most (if not all?) Di2 features that were removed from Hammerhead, so you will be able to view gears, control screen via Di2 button, have Di2 battery warnings.

**Comment by acoucke** [comment]
Thanks, appreciate it,
