### ISSUE TITLE
Support for Shimano E-Bike (STEPS EP-800 and EP-801)

### ISSUE THREAD

**Issue by NZ3-14** [valterc/ki2#208]
Hi,

Could you add support for Shimano STEPS E-Bike?

Thanks!

-Philip

**Comment by NZ3-14** [comment]
Just found the other issues on this topic.

**Comment by valterc** [comment]
Hi, the app supports STEPS but only the common data field with Di. There is no information related to power, range, speed, etc. Unfortunately I don't have a STEPS bike, so I cannot add that myself.

**Comment by NZ3-14** [comment]
Hi,

Thanks for the clarification.

Where are you located?

I’d be happy to cover the cost of renting a bike for a week or so if it
would help?

Best,

Philip
