### ISSUE TITLE
compiling test version...

### ISSUE THREAD

**Issue by proseLA** [valterc/ki2#210]
i am curious if everything that is needed to compile a running version of this code is available and up on this repository?

the last time i looked, i (and my java friends) had some trouble.  i even tried de-compiling the 5.0 release to see if the missing class files were there.

i would like to do some testing and am curious about creating new jar files.

appreciate any input.

**Comment by valterc** [comment]
Hi, as noted in the readme, all the code is available in the repository, expect one file:

> I tried cloning the repo but the build fails on my machine
>
> Yes, this is by design. There is a particular file missing from this repo and unfortunately I cannot add it here.

Like you said, you can perhaps obtain that file/value from some other location.
