### ISSUE TITLE
Process isn’t responding error

### ISSUE THREAD

**Issue by soldop** [valterc/ki2#213]
Release 5.0  Having issues at start up where I get “process isn’t responding” “close or wait” message. 
![IMG_3701](https://github.com/valterc/ki2/assets/76066425/e000dfc7-5815-4950-aaf2-66a926786f75)

**Comment by valterc** [comment]
That screenshot is about the System process, not seem related with Ki2?

**Comment by soldop** [comment]
Ok thank you

**Comment by valterc** [comment]
My suggestion would be to grab the logs from Karoo and see what is causing the issue. Use the Hammerhead support or community pages to find help: https://support.hammerhead.io/hc/en-us/community/topics

**Comment by soldop** [comment]
Hi. I have reached out and they propose to do a hard reset. However I chose to upgrade to 6.0 first and upon shutting down and restarting, the error message is now gone. 
I’ll keep an eye on things but for some reason your upgrade helped.
Thanks again for your effort on this project.
