### ISSUE TITLE
feature request: battery status graphic in gear display

### ISSUE THREAD

**Issue by robboyer** [valterc/ki2#216]
Not sure it's possible, but It would be cool if the Ki2 graphic gear display data field could include a small battery icon or simple bar graph showing the Di2 battery charge level.  I know the charge level is available as separate data field, but this would save a field...and could turn red when getting low, etc.

**Comment by valterc** [comment]
Hi Rob, that is a nice suggestion and totally possible. Let me sketch some designs and will come back to discuss.

**Comment by robboyer** [comment]
awesome, thanks for considering it!

**Comment by valterc** [comment]
Haven't had much time to work on this so far. Was thinking of what to change visually, probably the best is to follow HH design, this is what they have for gearing:

![image](https://github.com/valterc/ki2/assets/1299179/d32d2a61-02b5-4781-99da-e513fa5fb4d0)

Will try to update the gearing fields with a similar design.

**Comment by valterc** [comment]
Prototype:

![image](https://github.com/valterc/ki2/assets/1299179/13d8e771-05f8-40d0-bb48-616d82316fb0)
![image](https://github.com/valterc/ki2/assets/1299179/6b8e8654-7c78-40a1-867a-1aea65c2ea74)

Unfortunately we cannot make use of all the space like the default ones from hammerhead use.

**Comment by valterc** [comment]
![image](https://github.com/valterc/ki2/assets/1299179/4d11e23a-da47-4a88-ad93-9796b1749923)
![image](https://github.com/valterc/ki2/assets/1299179/5fab55cd-8589-46d3-a38b-b1923f5d6b60)
![image](https://github.com/valterc/ki2/assets/1299179/146fdfda-ea99-4551-8f5d-aa576811c792)
