### ISSUE TITLE
F gear and R gear not initially displaying in dark mode

### ISSUE THREAD

**Issue by ken-fyfe** [valterc/ki2#218]
Before shutting down my Karoo on my previous ride, I turned on dark screen mode. When I started it up again a few days later, the F gear and R gear data fields, on my default data screen, were not displaying. Other ki2 data fields and graphics were properly displaying in dark mode on other screens. 

Without turning off the Karoo, I then switched it to light mode and the F gear and R gear fields were now properly displaying. A couple of minutes later, again without shutting off the Karoo, I switched it back to dark mode and now the F gear and R gear fields were properly displaying!

So this workaround does work, but perhaps something is not properly initialized in dark mode for these data fields?

**Comment by valterc** [comment]
This will be fixed by the new version using Karoo Extensions. Will be available in the next few weeks.
