### ISSUE TITLE
Karoo 2 "D-Fly" switches recognized but not performing the assigned action

### ISSUE THREAD

**Issue by GrumpyMcAgryPants** [valterc/ki2#227]
Hi All,

I just installed Ki2 and everything works well except the switches. When i go into Ki2 settings and press the buttons it shows the press action (hold, click, double-click). When I assign them the actions (navigate left, right etc.) and try them out in my profile/ride....nothing happens. Am I missing something?

Thanks!
James

**Comment by Munka9** [comment]
you also need to make sure that the switch is assigned to the correct dfly channel in the Shimano e-tube app?

**Comment by valterc** [comment]
Closing as stale. The new version using Karoo Extensions will bring updated actions.
