### ISSUE TITLE
New version 7.0 Gear indicator color

### ISSUE THREAD

**Issue by dcquad** [valterc/ki2#229]
Hi, I'd love to be able to change the gear indicator color to something different to the light blue as it exists. I thought the original red was a better choice and more easily visible on the Karoo 2. The blue is waaay too washed out! I understand your idea was to more closely emulate the design cues of the sram gear indicator. It just isn't very good on the Karoo 2 screen.

thanks,  Doug

**Comment by kintrupf** [comment]
I also liked the old indicator color better 😊

**Comment by valterc** [comment]
Added an option to change the color of the gear indicator, you can choose from a few different colors

![image](https://github.com/user-attachments/assets/ac785ba7-7119-4b22-ac00-550be1473e6f)

This will be available on the next Ki2 version.

**Comment by valterc** [comment]
I just released Ki2 version [8.0](https://github.com/valterc/ki2/releases/tag/8.0) with this new option. Try it out and let me know of any feedback! 🙂

**Comment by pictoruws** [comment]
Thank you!!!


Sent from my BeOS tablet(forgive any typos)
________________________________
