### ISSUE TITLE
Karoo3 Switches

### ISSUE THREAD

**Issue by SeppDoDo** [valterc/ki2#230]
Hey,

i connected my GRX815 Di2 via Ki2 7.0 with my Karoo3. I understand that the data fields didnt work without the SDK on Karoo3. 

The switches are also not work? I tried it Map Zoom, Page Left/Right. Dont work. Is it also a SDK Problem or did i wrong?

Thanks a lot for this Great Software!

Best
sepp

**Comment by valterc** [comment]
Hi, unfortunately most of the features of Ki2 are currently designed around the availability/use of the SDK. 

Without the Karoo SDK none of the Ki2 features will be available in ride: no switch controls, no audio alerts, no overlay or data fields, no FIT gear recording, no battery alerts.

More info on #220
