### ISSUE TITLE
EP8 Support?

### ISSUE THREAD

**Issue by sfsanchez** [valterc/ki2#247]
Hi!

ki2 is great - thank you for creating this app! I've been using it on my Karoo 2 to connect the di2 units on my road and gravel bikes and it works great; however, I've never been able to get it to work properly with the EP8 unit on my 2022 Orbea Rise H15. I've read other threads where it has worked for people, so not sure why I can't get it to work properly. I'm running the latest firmware on all units - Karoo 2, EP8, and latest version of ki2. 

I can add the EP8 and connect to it (with good signal); however, it never loads data from the EP8 (just spinning wheels under the device details section). Eventually, one section will populate with the EP8 device details (serial number, software version, etc.), but the data never populates. I've have added the various data fields to the bike profile (including "SHF Bat %"), but the data never appears. 

Any ideas how I can fix this? I'm only looking to add the bike's battery percentage to my bike profile. 

Thank you!

Cheers,
Scott

Photos of screen...
![IMG_0033](https://github.com/user-attachments/assets/41385cce-f5fd-4337-b710-b7d8bd2e0c61)
![IMG_0034](https://github.com/user-attachments/assets/34471977-cd82-40b2-a7e2-a9ef6c768559)
![IMG_0035](https://github.com/user-attachments/assets/4a70c5a0-c0bb-49a4-b9d4-afe671aa1e13)

**Comment by sfsanchez** [comment]
Sorry. It's working now (AWESOME!). Not sure what happened - I let it sit overnight and now all is good. 

Thank you!

**Comment by valterc** [comment]
Hey, I didn't have a chance to reply, good that you solved the problem! 🙂 The di2/bike needs to be active to broadcast data.

Keep in mind that some features from EP8/Steps will not be available, for example data such as power and speed. Those fields should be available in the broadcasted data but we need to understand and obtain them. I don't have an EP8 bike so I cannot add those, if you are a developer feel free to help with that.

**Comment by sfsanchez** [comment]
Hi Valter,Thank you so much for the quick response. Yeah, it's working perfectly now. For the EP8, I only need it to show the batter % - so this is perfect. Unfortunately, I'm not a developer, so I don't have anything that I can offer other than saying thank you for creating this app! I've been following the SDK issue with the Karoo3. Hope fully, they will release it soon so your app can be available on the Karoo3. I definitely won't be getting the new unit until they make this change. Cheers,ScottOn Oct 15, 2024, at 3:49 AM, Valter Costa ***@***.***> wrote:﻿
Hey, I didn't have a chance to reply, good that you solved the problem! 🙂 The di2/bike needs to be active to broadcast data.
Keep in mind that some features from EP8/Steps will not be available, for example data such as power and speed. Those fields should be available in the broadcasted data but we need to understand and obtain them. I don't have an EP8 bike so I cannot add those, if you are a developer feel free to help with that.
