### ISSUE TITLE
Does the new SDK break Ki2? (1.524.2003)

### ISSUE THREAD

**Issue by markuuu** [valterc/ki2#253]
This is in the latest HH release notes:

"We added support for a new SDK, now called 'Hammerhead Extensions'. Third party developers are now able to build apps and extensions for Hammerhead riders. New Extensions are supported on both the new Karoo and Karoo 2.
- Previous apps built on the Karoo 2 SDK will not work with the new Extensions SDK."

Does this mean Ki2 will quit working if we upgrade our device to this release?

**Comment by valterc** [comment]
Ki2 seems to be working fine on 1.524.2003. The two SDKs on the device do not conflict with each other.

I'm working on porting the app to use the new SDK, will take some time, in the meantime the app is compatible with Karoo 2 just like before 🙂

**Comment by ronin1974** [comment]
Bom trabalho Valter :)
