### ISSUE TITLE
Wifi turned off when preload ride option enabled

### ISSUE THREAD

**Issue by JayUK** [valterc/ki2#38]
With the preload ride option enabled it turns off wfi but does not turn it back on.

Create an  option to re-enable it (if previously enabled) after the preload has happened.

**Comment by valterc** [comment]
Thanks, I noticed that too. 

Can you tell me which Ki2 version do you have installed? I tried to fix that in version 0.6. Let me know.

**Comment by JayUK** [comment]
I've just upgraded to 0.6 (was on 0.5) and the latest version has solved the Wi-Fi issue
