### ISSUE TITLE
Installing V0.7

### ISSUE THREAD

**Issue by s3dbw** [valterc/ki2#44]
Hi there, just tried installing the latest version, however getting the following error message. Does V0.6 have to be uninstalled first?

Thanks

![image](https://user-images.githubusercontent.com/81376784/205349096-15c1ce0b-2479-45e3-bae6-09de089b79da.png)

**Comment by valterc** [comment]
(You can uninstall before, in that case you will lose the added Di2 device and settings, instead) you should run the command with the **-r** argument, like so:
`adb.exe install -r "apps\ki2-0.7-release.apk"`

Let me know if that works. I'm working on auto updates for the next version :)

**Comment by s3dbw** [comment]
That did the trick. Auto updates would be brilliant. Thanks for all your efforts
