### ISSUE TITLE
Reddit traction

### ISSUE THREAD

**Issue by spencertollefson** [valterc/ki2#46]
Not an issue, but wanted to let you know that I think you may have gotten some new traction today from a reddit thread. Thanks for making and sharing this project!

reddit.com/r/Karoo/comments/zadz78/ki2_app_for_karoo_to_restore_di2_functionality/

**Comment by byronbrewer** [comment]
That's how I landed here.

Thank you so much for your efforts!

**Comment by valterc** [comment]
Thanks folks 🙂 I saw the posts on reddit and facebook. I wanted to keep a low profile until the app is a bit more solid and tested, but I guess the beans are spilled now 😁 

(Hopefully HH keeps supporting the Karoo SDK)

**Comment by Ruud-C** [comment]
Great stuff, thank you! Your work is much appreciated.

**Comment by valterc** [comment]
Enjoy guys. If you have problems or suggestions, feel free to reach out!
