### ISSUE TITLE
Two Simultaneously Connected Di2 Causes Looping between devices

### ISSUE THREAD

**Issue by haspden** [valterc/ki2#74]
Opening a Di2 when two devices are connected Simultaneously causes the
- battery
- signal strength
- serial number
- model number
- gears
- etc

And other related data to flicker rapidly between the two active connections.

Clicking on the device appears to open all active connections not be filtered by decice ID / serial number of the one clicked upon.

See video attached

https://user-images.githubusercontent.com/4039041/209569989-848c2dd6-65e5-43c9-b721-e44097bca4f9.mp4

**Comment by valterc** [comment]
Thanks for reporting 🙂 I was already aware of this problem and started working to fix it in #72. Still need to do some more work, until a new release comes, better to have a single device added/connected at a time.

**Comment by haspden** [comment]
> Thanks for reporting 🙂 I was already aware of this problem and started working to fix it in #72. Still need to do some more work, until a new release comes, better to have a single device added/connected at a time.

Thanks @valterc , yes just noticed it today whilst adding a second bike whilst giving them all a nice winter strip down, clean and rebuild

**Comment by valterc** [comment]
Fixed now, I still need to test other things on the road, it might take some days until it's released.
