### ISSUE TITLE
Add support for Hood buttons even when Ki2 data elements are not present in the ride profile

### ISSUE THREAD

**Issue by judahrand** [valterc/ki2#85]
I had expected that even if I don't have a Ki2 data element on a ride profile the hood buttons should work if "Pre load ride application" setting is enabled. However, this does not seem to be the case - a Ki2 data element must be present.

**Comment by valterc** [comment]
That is indeed correct @judahrand, for the hood buttons to work you will need at least one Ki2 data element in the ride profile. I can try to make them work anytime inside the ride app, but I cannot guarantee it will work reliably.

**Comment by judahrand** [comment]
I see. It's not really a bit deal as one can just have a screen with just Di2 battery or something but it would be nice for it to 'just work'. I'm familiar with these sorts of limitations as they exist with some Garmin ConnectIQ applications.
