### ISSUE TITLE
No audio alerts for synchro shifting

### ISSUE THREAD

**Issue by ronin1974** [valterc/ki2#95]
I dont have the audio alert on the synchro shifting, only on the max and lower gear.
I´m using the 1.0 version and the latest firmware from Hammerhead: Build Version 1.352.1409

**Comment by ronin1974** [comment]
- Do you have that setting enabled in Ki2? yes
   - Do you have Di2 shifting in S2 mode? yes
   - What is you Di2 setup? Is it up-to-date and well configured in E-Tube
   ? yes


Em seg., 16 de jan. de 2023 às 16:38, Valter Costa ***@***.***>
escreveu:

**Comment by ronin1974** [comment]
I´ve tested again your ki2 and the lower and higher beeps still sound even
if they are switched off



Em seg., 16 de jan. de 2023 às 16:38, Valter Costa ***@***.***>
escreveu:

**Comment by ronin1974** [comment]
Hi,

I updated from the v0.9 directly from the appI i turn off and restarted the
Karoo

After that I went for a ride.



Em seg., 16 de jan. de 2023 às 19:19, Valter Costa ***@***.***>
escreveu:

**Comment by valterc** [comment]
I was able to reproduce some problems with the alerts. Should be fixed now, I still need to go out for a ride to test. Will be available in the next update.
